### ISSUE TITLE
txt file on how to import to godot4

### ISSUE THREAD

**Issue by jonSP12** [feendrache/Godot4-TiledImporter#1]
Hello, 
Any chance to add some notes, Like the one in the tiled importer for the 3.5

for example:
How to save the tile map in tiled ?? ( godot tile map format *.tcsn or * tmx )
Witch files need to be dragged into godot ?

Ive been looking into my 3.5 project, and into all the tiled levels i passed there... 
And i can find 1 file ( *.tmx ) for each tile layer... Iam seeing in 3.5 each tile layer, back/ middle / front was saved on a seperate  ( *.tmx )
![tiled](https://user-images.githubusercontent.com/77213594/213405420-ae328c6f-de90-4d25-83f4-4a81e239ad8e.png)

**Comment by Kiamo2** [comment]
Looking into the code I'd suggest it works with .tmx and .tsx (these are XML format files).
-> Dragged into Godot must be the .tmx (tile map) and - if not embedded - all used .tsx files (tile sets)
-> AND of course all used pictures (.png)
Beware: Relative paths (e.g. the path to the .tsx etc.) must be correct!
A test would be if the dragged files are loadable into Tiled without s.th. missing.
If needed you could edit the .tmx and .tsx to correct paths.
Good luck :-)

**Comment by jonSP12** [comment]
> Looking into the code I'd suggest it works with .tmx and .tsx (these are XML format files). -> Dragged into Godot must be the .tmx (tile map) and - if not embedded - all used .tsx files (tile sets) -> AND of course all used pictures (.png) Beware: Relative paths (e.g. the path to the .tsx etc.) must be correct! A test would be if the dragged files are loadable into Tiled without s.th. missing. If needed you could edit the .tmx and .tsx to correct paths. Good luck :-)

thanks

I dont mind redrawing all the tiled levels from scratch.
All the tile files there i was just testing some levels on 3.5

My problem is i dont know witch files to drag on to godot ?
I already have all the tile images .png in godot 4.

But using tiled i think it creates a file for each image.png
and a file for each tilemap level ( *.tmx )

Ive already dragged a *.tmx file into godot4, but nothing happens it doesnt reconize the file

**Comment by feendrache** [comment]
I created a small txt: https://github.com/feendrache/Godot4-TiledImporter/blob/main/short-notes-how-to-use.txt
But essentially you need the tmx-file with all the layers, just this one and the referenced tsx ... 
And sometimes it takes some time for godot to find the file or the importer to start... sometimes it helps to open the tiled map in tiled (inside the project structure) und save it again in tiled to let godot recognise the file

This was already the case in the 3.5 version

**Comment by jonSP12** [comment]
thanks,
I think i know were the problem is...
my plugins folder was empty

![tiled0](https://user-images.githubusercontent.com/77213594/213421657-6849db12-0e7f-4206-9f25-85a1b01af5fd.png)


//-----------------///---------------//----------

Ive draggen the plug in into the addons folder, but iam getting an error

Unable to load addon script from path: 'res://addons/naddys_tiled_maps/naddys_tiled_maps.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/naddys_tiled_maps/plugin.cfg' to prevent further errors.

![tiled](https://user-images.githubusercontent.com/77213594/213421825-f424d506-9da4-47ab-84d5-33e32f5bd4b7.png)


[edit]
the LICENSE file doesnt show in the tree, but its there
![tiled2](https://user-images.githubusercontent.com/77213594/213426603-243c14a7-70ca-411a-b509-8fadba23bb1a.png)

**Comment by Kiamo2** [comment]
No real clue, for me it basically worked.
Are you sure you're using Godot 4 and not 3.5?

**Comment by feendrache** [comment]
yeah please check your godot version... i'm currently on beta 13 in godot 4 and it simply works

**Comment by jonSP12** [comment]
yeah,  i was using beta10...
Just tried on beta13 and its working 

![tile](https://user-images.githubusercontent.com/77213594/213507879-0bbd1fc7-5495-4257-a5bc-bba19ffee6fd.png)

**Comment by feendrache** [comment]
yeah, great.
I will take care to state the Subversion in the ReadMe as soon as Godot 4 is out of Beta
