### ISSUE TITLE
Imported tilemap looking wrong

### ISSUE THREAD

**Issue by Kiamo2** [feendrache/Godot4-TiledImporter#2]
Original (from Tiled):

![Original](https://user-images.githubusercontent.com/122157211/213517777-e5518550-c959-477a-9ee5-5cdc55d9c0ba.png)

Imported result:

![Imported](https://user-images.githubusercontent.com/122157211/213517889-eea93398-19af-43d8-9ee0-18854fddd054.png)

Tile size is 32x32
Seems as if the tiles would be placed too tight together but I'm not quite sure, what's the exact problem is...
Regards

**Comment by feendrache** [comment]
are you using a free tileset? if yes can you give me the link than i can test directly with this tileset.
Will look into it

**Comment by Kiamo2** [comment]
Unfortunately it's not a free one, I bought it.
-> I could try to find a free tileset and build an example but this could take some time, free ones seem to be preferably 16x16.
(I suspect that 16x16 do work and only bigger tile sizes are a problem)

**Comment by feendrache** [comment]
yeah ok, i will get me a 32x32 tileset thats free to test it, may take me a bit of time thought, pretty busy right now

**Comment by Kiamo2** [comment]
Ah, found it out!
File 'tileset_creator.gd' contains in line 131:
\# tileset.tile_size = tilesize
Removing the '#' solved it.

**Comment by feendrache** [comment]
gah... thx... removed the #
