### ISSUE TITLE
tileSet is always set 16x16

### ISSUE THREAD

**Issue by jonSP12** [feendrache/Godot4-TiledImporter#3]
Maybe its a version problem... ?
Iam using 1.8.

No matter how many times i save the imported tileSet is always set to 16x16

![tl01](https://user-images.githubusercontent.com/77213594/213860371-dd14ea6c-2023-41dc-8d27-9e0a457c7549.png)

Ive tried to search but cant fin any refence to tilewidth, tileheight... in the tileSet scripts

the properties in tiled are 32

![tl02](https://user-images.githubusercontent.com/77213594/213860413-ecb4f6e7-90b1-4ea6-b2d0-a22efda06f9b.png)

I cant find any refence in the tileSet script's for this line, the with and height for the tileSet

![tl03](https://user-images.githubusercontent.com/77213594/213860459-bcf51b02-683e-426a-ab68-cfad1509f05c.png)

**Comment by jonSP12** [comment]
just saw the other post here:
Imported tilemap looking wrong #2

it worked, 
tileset_creator.gd, line 131, removing the "#" in "tileset.tile_size = tilesize"

**Comment by feendrache** [comment]
Removed the # in the file
