### ISSUE TITLE
Some Non-Square Tilesets are being offset when imported to Godot

### ISSUE THREAD

**Issue by TheBeardedBerry** [feendrache/Godot4-TiledImporter#4]
![image](https://user-images.githubusercontent.com/7057201/215611884-a18110f1-f3ad-4807-953d-c43c36267aff.png)

When importing a map from Tiled to Godot there seems to be a subtile offset on some non-square tileset assets in the longer direction. I say "some" because I've not noticed the issue on all non-square tileset assets.

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/7057201/215612959-e146ca05-57a2-491a-a8d5-73bfb81fc1d2.png">

For example, above, same image as before but now you can see the trees in between tiled and godot and the tree doesnt seem to have issues.

Notes:
- In Godot, if you adjust the Texture Region Size in the tile set, the tileset will clip to the top cel from the original placement and the texture will shift down so the top half of the texture is properly in the frame of the top cel.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/7057201/215613465-c70aed1b-aee9-4f0f-84cd-6998c29466a6.png">

- In Godot, if I try and place one of the assets from the tileset with the issue into the map in Godot, It will appear to snap halfway between the cels. (see image below. Note that the cursor is missing so i pointed to the unplaced tile with an orange arrow)

<img width="1155" alt="Screenshot 2023-01-30 at 14 48 16" src="https://user-images.githubusercontent.com/7057201/215613966-d5526004-e687-4b3f-baff-3bc9dc8d47c4.png">

Please let me know if you need more info or if you'd like to hop on a video call or something. Im happy to help however i can. ^_^

**Comment by feendrache** [comment]
I added a "force tilesize" option to the tilemap importer. Please try again with this option activated and the base tileset set to your small tile size.

**Comment by feendrache** [comment]
I updated to Beta 17 compability, please test again
